/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "calculator-test.check" instead.
 */

#include <check.h>

#line 1 "calculator-test.check"
/* 
Roman calculator: performs addition and subtraction of roman values
Author: Vinay vittal Karagod
File dependents: main.c, calculator.h, calculator.c,calculator-test.check
Date: 09/06/2016
calculator-test.check: Test file used to pass the input values to calculate roman numbers.
*/

# include "calculator.h"


START_TEST(calc)
{
#line 13

/* checking the conditions for the single roman value*/
ck_assert_msg(romanValue('I') == 1,"operation failed for I");
ck_assert_msg(romanValue('V') == 5,"operation failed for V");
ck_assert_msg(romanValue('X') == 10,"operation failed for X");
ck_assert_msg(romanValue('L') == 50,"operation failed for L");
ck_assert_msg(romanValue('C') == 100,"operation failed for C");
ck_assert_msg(romanValue('D') == 500,"operation failed for D");
ck_assert_msg(romanValue('M') == 1000,"operation failed for M");
ck_assert_msg(romanValue('\0') == 0,"operation failed for end of line");
ck_assert_msg(romanValue('K') == -1,"operation failed for passing empty file");


/*condition to check the string of roman numbers*/
ck_assert_msg(roman_decimal("MD") == 1500,"operation failed to convert roman to decimal");




}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
